# Generated by Django 5.2.4 on 2025-08-12 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0001_initial'),
        ('tickets', '0003_ticket_closed_at_ticket_closure_summary_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision_type', models.CharField(choices=[('resolve', 'Resolve'), ('close', 'Close')], max_length=50)),
                ('decision', models.CharField(choices=[('approved', 'Approved'), ('declined', 'Declined')], max_length=10)),
                ('decision_notes', models.TextField(blank=True, null=True)),
                ('decision_time', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agents.agent')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.ticket')),
            ],
        ),
    ]
