# Generated by Django 5.2.4 on 2025-08-27 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0001_initial'),
        ('agents', '0002_agentmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admindecision',
            name='admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agents.agent'),
        ),
        migrations.AlterField(
            model_name='admindecision',
            name='decision',
            field=models.CharField(choices=[('approved', 'Approved'), ('declined', 'Declined'), ('final', 'Final')], max_length=10),
        ),
    ]
