# Generated by Django 5.2.4 on 2025-08-03 20:14

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(db_index=True, unique=True)),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('language_code', models.CharField(blank=True, max_length=10, null=True)),
                ('open_ticket', models.BooleanField(default=False)),
                ('banned', models.BooleanField(default=False)),
                ('open_ticket_spam', models.IntegerField(default=1)),
                ('open_ticket_link', models.CharField(blank=True, max_length=255, null=True)),
                ('open_ticket_time', models.DateTimeField(default=datetime.datetime(1000, 1, 1, 0, 0))),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_text', models.TextField()),
                ('message_type', models.CharField(default='text', max_length=50)),
                ('telegram_message_id', models.BigIntegerField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='customers.customer')),
            ],
        ),
    ]
