# Generated by Django 5.2.4 on 2025-08-06 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customermessage',
            name='is_forwarded',
            field=models.BooleanField(default=False),
        ),
    ]
