# Generated by Django 5.2.4 on 2025-08-06 20:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customermessage_is_forwarded'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customermessage',
            name='is_forwarded',
        ),
        migrations.AlterField(
            model_name='customer',
            name='open_ticket_time',
            field=models.DateTimeField(default=datetime.datetime(1000, 1, 1, 0, 0, tzinfo=datetime.timezone.utc)),
        ),
    ]
