# Generated by Django 5.2.4 on 2025-08-12 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_customermessage_is_forwarded_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customermessage',
            name='is_closed_message',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customermessage',
            name='is_resolved_message',
            field=models.BooleanField(default=False),
        ),
    ]
