# Generated by Django 5.2.4 on 2025-08-19 18:33

import customers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_customermessage_is_closed_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='open_ticket_time',
            field=models.DateTimeField(default=customers.models.get_default_open_ticket_time),
        ),
    ]
