# Generated by Django 5.2.4 on 2025-08-25 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_alter_customer_open_ticket_time'),
        ('tickets', '0003_ticket_closed_at_ticket_closure_summary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customermessage',
            name='ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='tickets.ticket'),
        ),
    ]
